Repository daydreamplace/VocaVocca, pull requests merged in 2025-01, with the labels that each got.

#16 [#6] Custom Button 구현
  VocaVocca/View/CustomView/CustomButton.swift
Labels: feature

#17 [#9] CustomTagView 구현
  VocaVocca/View/CustomView/CustomTagView.swift
Labels: feature

#19 [#8] CustomCardView 구현
  VocaVocca/View/CustomView/CustomCardView.swift
Labels: feature

#20 [#1] NetworkManager 구현
  VocaVocca.xcodeproj/project.pbxproj
  VocaVocca/Model/Language.swift
  VocaVocca/Model/NetworkManager.swift
  VocaVocca/Model/TranslationsResponse.swift
  VocaVocca/Resource/Info.plist
Labels: feature

#21 [#3] UserDefaultsManager 구현
  VocaVocca/Model/UserDefaultsManager.swift
Labels: feature

#22 [#5] LearningViewController UI 기본 구현
  VocaVocca/View/Learning/LearningViewCell.swift
  VocaVocca/View/Learning/LearningViewController.swift
Labels: feature

#23 [#15] RecordViewController UI 기본 구현
  VocaVocca/View/Record/RecordResultViewController.swift
Labels: feature

#24 [#18] LearningResultViewController UI 기본 구현
  VocaVocca/View/Learning/LearningResultViewController.swift
Labels: feature

#25 [#10] CoreDataManager CRUD 구현
  VocaVocca/Model/CoreDataManager.swift
  VocaVocca/Model/RecordData+CoreDataClass.swift
  VocaVocca/Model/RecordData+CoreDataProperties.swift
  VocaVocca/Model/RecordData.swift
  VocaVocca/Model/VocaBookData+CoreDataClass.swift
  VocaVocca/Model/VocaBookData+CoreDataProperties.swift
  VocaVocca/Model/VocaData+CoreDataClass.swift
  VocaVocca/Model/VocaData+CoreDataProperties.swift
  VocaVocca/Model/VocaData.swift
  VocaVocca/VocaVocca.xcdatamodeld/VocaVocca.xcdatamodel/contents
Labels: feature

#28 [#26] 탭바 구현
  VocaVocca/App/SceneDelegate.swift
  VocaVocca/View/Record/RecordResultViewController.swift
  VocaVocca/View/Record/RecordViewController.swift
  VocaVocca/View/Voca/VocaMainViewController.swift
Labels: feature

#32 [#31] 플래시카드 화면 UI 구현
  VocaVocca/View/Learning/FlashcardView.swift
  VocaVocca/View/Learning/FlashcardViewController.swift
Labels: feature

#36 [#14] CustomModalView 구현
  VocaVocca.xcodeproj/project.pbxproj
  VocaVocca/View/CustomView/CustomButton.swift
  VocaVocca/View/CustomView/CustomModalView.swift
Labels: feature

#38 [#27] VocaBookSelectView UI 구현
  VocaVocca/View/CustomView/CustomTagView.swift
  VocaVocca/View/Voca/VocaBookSelectCell.swift
  VocaVocca/View/Voca/VocaBookSelectView.swift
  VocaVocca/View/Voca/VocaBookSelectViewController.swift
Labels: feature

#41 [#35] 코치마크 화면 UI 구현
  VocaVocca/View/Learning/CoachmarkView.swift
  VocaVocca/View/Learning/CoachmarkViewController.swift
  VocaVocca/View/Learning/FlashcardViewController.swift
Labels: feature

#43 [#40] 학습메인, 학습결과, 기록메인 뷰, 뷰컨 분리 및 코드수정
  VocaVocca/View/Learning/LearningResultView.swift
  VocaVocca/View/Learning/LearningResultViewController.swift
  VocaVocca/View/Learning/LearningView.swift
  VocaVocca/View/Learning/LearningViewController.swift
  VocaVocca/View/Record/RecordView.swift
  VocaVocca/View/Record/RecordViewController.swift
  VocaVocca/View/Voca/VocaBookSelectCell.swift
  VocaVocca/View/Voca/VocaBookSelectView.swift
  VocaVocca/View/Voca/VocaBookSelectViewController.swift
Labels: refactor

#45 [#29] VocaMainView UI 구현
  VocaVocca/View/Voca/VocaMainTableViewCell.swift
  VocaVocca/View/Voca/VocaMainView.swift
  VocaVocca/View/Voca/VocaMainViewController.swift
Labels: feature

#46 [#44] Entity relationships 수정
  VocaVocca/Model/CoreDataManager.swift
  VocaVocca/Model/RecordData+CoreDataProperties.swift
  VocaVocca/Model/VocaBookData+CoreDataProperties.swift
  VocaVocca/Model/VocaData+CoreDataProperties.swift
  VocaVocca/VocaVocca.xcdatamodeld/VocaVocca.xcdatamodel/contents
Labels: feature

#47 [#39] VocaBookModalViewController 구현
  VocaVocca/Model/Language.swift
  VocaVocca/View/CustomView/CustomModalView.swift
  VocaVocca/View/CustomView/CustomTextFieldView.swift
  VocaVocca/View/Voca/VocaBookModalViewController.swift
  VocaVocca/View/Voca/VocaMainViewController.swift
Labels: feature

#49 [#48] VocaModalViewController 구현
  VocaVocca/View/Voca/VocaModalViewController.swift
Labels: feature

#52 [#42] coachmark 비활성화 기능 구현
  VocaVocca.xcodeproj/project.pbxproj
  VocaVocca/Model/UserDefaultsManager.swift
  VocaVocca/View/Learning/CoachmarkViewController.swift
  VocaVocca/View/Learning/FlashcardViewController.swift
  VocaVocca/ViewModel/Learning/CoachmarkViewModel.swift
  VocaVocca/ViewModel/Learning/FlashcardViewModel.swift
Labels: feature

#57 [#50] VocaBookModalViewModel 구현
  VocaVocca.xcodeproj/project.pbxproj
  VocaVocca/View/CustomView/CustomModalView.swift
  VocaVocca/View/CustomView/CustomTextFieldView.swift
  VocaVocca/View/Voca/VocaBookModalViewController.swift
  VocaVocca/ViewModel/Voca/VocaBookModalViewModel.swift
Labels: feature

#58 [#56] 학습메인 뷰모델 구현, 테스트
  VocaVocca/View/Learning/LearningView.swift
  VocaVocca/View/Learning/LearningViewCell.swift
  VocaVocca/View/Learning/LearningViewController.swift
  VocaVocca/ViewModel/Learning/LearningViewModel.swift
Labels: feature

#60 [#53] 단어 전환 기능 구현
  VocaVocca/View/Learning/FlashcardView.swift
  VocaVocca/View/Learning/FlashcardViewController.swift
  VocaVocca/View/Learning/LearningViewController.swift
  VocaVocca/ViewModel/Learning/FlashcardViewModel.swift
  VocaVocca/ViewModel/Learning/LearningViewModel.swift
Labels: feature

#62 [#61] 플래시카드 화면에 결과 화면 연결
  VocaVocca.xcodeproj/project.pbxproj
  VocaVocca/Model/LearningResult.swift
  VocaVocca/View/Learning/FlashcardViewController.swift
  VocaVocca/View/Learning/LearningResultViewController.swift
  VocaVocca/ViewModel/Learning/FlashcardViewModel.swift
  VocaVocca/ViewModel/Learning/LearningResultViewModel.swift
Labels: feature

#67 [#54] VocaMainViewController 화면 연결 및 CustomCardView 수정
  VocaVocca/View/CustomView/CustomCardView.swift
  VocaVocca/View/Voca/VocaMainTableViewCell.swift
  VocaVocca/View/Voca/VocaMainView.swift
  VocaVocca/View/Voca/VocaMainViewController.swift
  VocaVocca/ViewModel/Voca/VocaMainViewModel.swift
Labels: feature

#69 [#59] VocaModalViewModel 구현
  VocaVocca/View/CustomView/CustomButton.swift
  VocaVocca/View/CustomView/CustomTextFieldView.swift
  VocaVocca/View/Voca/VocaMainView.swift
  VocaVocca/View/Voca/VocaMainViewController.swift
  VocaVocca/View/Voca/VocaModalViewController.swift
  VocaVocca/ViewModel/Voca/VocaMainViewModel.swift
  VocaVocca/ViewModel/Voca/VocaModalViewModel.swift
Labels: feature

#70 [#64] 학습 결과 화면 데이터 연결
  VocaVocca/View/Learning/FlashcardViewController.swift
  VocaVocca/View/Learning/LearningResultView.swift
  VocaVocca/View/Learning/LearningResultViewController.swift
  VocaVocca/ViewModel/Learning/FlashcardViewModel.swift
  VocaVocca/ViewModel/Learning/LearningResultViewModel.swift
Labels: feature

#74 [#72] 학습결과 정답률에 따른 이미지 설정
  VocaVocca/View/Learning/LearningResultView.swift
  VocaVocca/View/Learning/LearningResultViewController.swift
  VocaVocca/View/Learning/LearningViewController.swift
  VocaVocca/ViewModel/Learning/LearningResultViewModel.swift
  VocaVocca/ViewModel/Learning/LearningViewModel.swift
Labels: feature

#77 [#73] 기록 데이터 중복 저장 문제 해결
  VocaVocca/Model/CoreDataManager.swift
  VocaVocca/ViewModel/Learning/FlashcardViewModel.swift
Labels: fix

#79 [#75] 단어장 선택 뷰모델 1차 구현
  VocaVocca/View/Voca/VocaBookSelectCell.swift
  VocaVocca/View/Voca/VocaBookSelectView.swift
  VocaVocca/View/Voca/VocaBookSelectViewController.swift
  VocaVocca/ViewModel/Learning/LearningViewModel.swift
  VocaVocca/ViewModel/Voca/VocaBookSelectViewModal.swift
  VocaVocca/ViewModel/Voca/VocaBookSelectViewModel.swift
Labels: feature

#81 [#78] 플래시카드 스와이프 기능 구현
  VocaVocca.xcodeproj/project.pbxproj
  VocaVocca.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  VocaVocca/View/Learning/FlashcardView.swift
  VocaVocca/View/Learning/FlashcardViewController.swift
Labels: feature

#82 [#68] 메인화면 UI 수정 및 데이터 연결
  VocaVocca/Model/UserDefaultsManager.swift
  VocaVocca/View/Voca/VocaMainTableViewCell.swift
  VocaVocca/View/Voca/VocaMainViewController.swift
  VocaVocca/ViewModel/Voca/VocaMainViewModel.swift
  VocaVocca/ViewModel/Voca/VocaModalViewModel.swift
Labels: feature, fix

#84 [#83] 로고이미지 추가 및 적용
  VocaVocca/Resource/Assets.xcassets/logoImage.imageset/Contents.json
  VocaVocca/Resource/Assets.xcassets/logoImage.imageset/커피콩.png
  VocaVocca/View/Learning/LearningResultView.swift
Labels: feature

#88 [#85] 선택 에러 시, 토스트 메세지 기능 구현
  VocaVocca/View/Learning/LearningView.swift
  VocaVocca/View/Learning/LearningViewController.swift
  VocaVocca/ViewModel/Learning/LearningViewModel.swift
Labels: feature

#86 [#80] ViewModel 데이터 바인딩 및 컨트롤러 연동 구현
  VocaVocca/View/Record/RecordResultViewController.swift
  VocaVocca/View/Record/RecordView.swift
  VocaVocca/View/Record/RecordViewController.swift
  VocaVocca/ViewModel/Record/RecordResultViewModel.swift
  VocaVocca/ViewModel/Record/RecordViewModel.swift
Labels: feature

#89 [#71] VocaModalViewController의 CoreData, NetworkManager연결
  VocaVocca.xcodeproj/project.pbxproj
  VocaVocca.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  VocaVocca/Model/NetworkManager.swift
  VocaVocca/View/CustomView/CustomModalView.swift
  VocaVocca/View/CustomView/CustomTextFieldView.swift
  VocaVocca/View/Voca/VocaBookModalViewController.swift
  VocaVocca/View/Voca/VocaBookSelectViewController.swift
  VocaVocca/View/Voca/VocaMainViewController.swift
  VocaVocca/View/Voca/VocaModalViewController.swift
  VocaVocca/ViewModel/Voca/VocaBookSelectViewModel.swift
  VocaVocca/ViewModel/Voca/VocaModalViewModel.swift
Labels: feature

#93 [#91] 코어데이터 언어선택 관련 수정
  VocaVocca/Model/CoreDataManager.swift
  VocaVocca/Model/VocaBookData+CoreDataProperties.swift
  VocaVocca/Model/VocaData+CoreDataProperties.swift
  VocaVocca/ViewModel/Learning/LearningViewModel.swift
  VocaVocca/ViewModel/Voca/VocaBookModalViewModel.swift
  VocaVocca/ViewModel/Voca/VocaModalViewModel.swift
  VocaVocca/VocaVocca.xcdatamodeld/VocaVocca.xcdatamodel/contents
Labels: fix

#100 [#68] 단어 삭제 구현
  VocaVocca/View/Voca/VocaMainTableViewCell.swift
  VocaVocca/View/Voca/VocaMainViewController.swift
  VocaVocca/ViewModel/Voca/VocaMainViewModel.swift
Labels: feature

#101 [#87] 단어장선택뷰 삭제구현
  VocaVocca/View/Learning/LearningViewController.swift
  VocaVocca/View/Voca/VocaBookSelectViewController.swift
  VocaVocca/ViewModel/Learning/LearningViewModel.swift
  VocaVocca/ViewModel/Voca/VocaBookSelectViewModel.swift
Labels: feature

#102 [#94] 셀 선택 스타일 제거 및 화면 전환 애니메이션 개선
  VocaVocca/View/Record/RecordResultViewController.swift
  VocaVocca/View/Record/RecordView.swift
  VocaVocca/ViewModel/Record/RecordResultViewModel.swift
Labels: feature

#103 [#98] VocaModalViewModel 단어 번역 API 메서드 수정
  VocaVocca/Model/Language.swift
  VocaVocca/View/Voca/VocaBookModalViewController.swift
  VocaVocca/View/Voca/VocaBookSelectViewController.swift
  VocaVocca/View/Voca/VocaModalViewController.swift
  VocaVocca/ViewModel/Voca/VocaBookModalViewModel.swift
  VocaVocca/ViewModel/Voca/VocaModalViewModel.swift
Labels: fix

#104 [#91] 단어장 삭제 등 수정
  VocaVocca/App/SceneDelegate.swift
  VocaVocca/View/CustomView/CustomCardView.swift
  VocaVocca/View/Learning/LearningViewController.swift
  VocaVocca/View/Voca/VocaBookSelectCell.swift
  VocaVocca/View/Voca/VocaBookSelectViewController.swift
  VocaVocca/View/Voca/VocaMainTableViewCell.swift
  VocaVocca/View/Voca/VocaMainViewController.swift
  VocaVocca/ViewModel/Voca/VocaBookModalViewModel.swift
  VocaVocca/ViewModel/Voca/VocaBookSelectViewModel.swift
  VocaVocca/ViewModel/Voca/VocaMainViewModel.swift
Labels: feature, fix

#107 [#106] 해당 단어에 언어 정보를 태그 형태로 표시
  VocaVocca/View/Record/RecordResultViewController.swift
  VocaVocca/View/Record/RecordViewController.swift
  VocaVocca/ViewModel/Record/RecordResultViewModel.swift
Labels: refactor

#108 [#68] 메인화면 UI 수정
  VocaVocca/Resource/Assets.xcassets/button.imageset/Contents.json
  VocaVocca/Resource/Assets.xcassets/button.imageset/button.png
  VocaVocca/Resource/Assets.xcassets/logoImage.imageset/커피콩.png
  VocaVocca/View/CustomView/CustomCardView.swift
  VocaVocca/View/Voca/VocaBookSelectView.swift
  VocaVocca/View/Voca/VocaMainView.swift
  VocaVocca/View/Voca/VocaMainViewController.swift
Labels: fix

#110 [#109] 셀 선택 시 색상 변경 수정
  VocaVocca/Model/Language.swift
  VocaVocca/View/CustomView/CustomTagView.swift
  VocaVocca/View/Learning/LearningViewCell.swift
  VocaVocca/View/Learning/LearningViewController.swift
  VocaVocca/View/Record/RecordResultViewCell.swift
  VocaVocca/View/Record/RecordResultViewController.swift
  VocaVocca/View/Voca/VocaBookSelectCell.swift
  VocaVocca/View/Voca/VocaMainViewController.swift
Labels: refactor
